# Generated by Django 5.2.5 on 2025-08-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "flashcards_app",
            "0002_remove_deck_user_remove_feedback_user_deck_user_id_and_more",
        ),
    ]

    operations = []
